version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/docker_postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
  postgres:
    image: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=docker_postgres
    networks:
      - backend
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
volumes:
  db:
    driver: local
networks:
  backend:
    driver: bridge